/*  Lance l''application i_builder                                        */
/*  bibliothèques système                                                 */
/*  CPP:  GSTLOT10                                                        */
      /* >>PRE-COMPILER<<                                                 */
      /*   >>CRTCMD<<  CRTCMD CMD(&LI/&OB) SRCFILE(&SL/&SF) +             */
      /*                 SRCMBR(&SM);                                     */
      /*   >>IMPORTANT<<                                                  */
      /*     >>PARM<<  PGM(&LI/&OB);                                      */
      /*     >>PARM<<  TGTRLS(*CURRENT);                                  */
      /*   >>END-IMPORTANT<<                                              */
      /*   >>EXECUTE<<                                                    */
      /* >>END-PRE-COMPILER<<                                             */

             CMD        PROMPT('i_Builder') PRDLIB(I_BUILDER)
