-- >>PRE-COMPILER<<                                              */
--   >>CRTCMD<<  RUNSQLSTM SRCFILE(&SL/&SF) SRCMBR(&SM);         */
--   >>IMPORTANT<<                                               */
--     >>PARM<<  COMMIT(*NONE);                                  */
--     >>PARM<<  NAMING(*SQL);                                   */
--     >>PARM<<  DFTRDBCOL(&LI);                                 */
--   >>END-IMPORTANT<<                                           */
--   >>EXECUTE<<                                                 */
-- >>END-PRE-COMPILER<<                                          */

-- Ajout de lien internet  
ALTER TABLE LOTS ALTER COLUMN LIBELLE_LOTS 
    SET DATA TYPE VARCHAR (128 ) CCSID 1147 
                             NOT NULL WITH DEFAULT '';                     